version: '3.8'

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: <Usename>
      MONGO_INITDB_ROOT_PASSWORD: <Password>
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
