version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped 
    environment:
      POSTGRES_USER: <Username>
      POSTGRES_PASSWORD: <Password>
      POSTGRES_DB: <Root Password>
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
